version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - crossfade
  - fairseq
  - faiss
  - interp
  - medfilt
  - parselmouth
  - pitchf
  - pyworld
  - resampy
  - rint
  - scipy
  - stonemask
  - unsqueeze
  - w-okada
  - liujing04
  - esnya
ignoreWords: []
import: []
